FORMAT: 1A
HOST: http://kb.phenoscape.org/api/

# Phenoscape Knowledgebase web API
The Phenoscape Knowledgebase web API is an HTTP interface for searching ontology terms, retrieving term info, and querying data from the KB.

# Group Knowledgebase status

##  KB annotation summary [/annotation_summary]
### Return summary counts of annotated data matrices, taxa, characters, and states [GET]
+ Response 200 (application/json)

        {
        "annotated_matrices": 154,
        "annotated_taxa": 5071,
        "annotated_characters": 9602,
        "annotated_states": 21182
        }
        
##  KB annotation report [/annotation_report]
### Return table of character state EQ annotations for curator review [GET]
The columns are tab-separated.
+ Response 200 (text/plain)

        ?matrix_file  ?character_number  ?character_text  ?state_symbol  ?state_text  ?entity_id  ?entity_name  ?quality_id  ?quality_name  ?related_entity_id  ?related_entity_name  ?attributes
        "Bowne, P. S. (1994)"  "7"  "Interorbital commissure"  "1"  "medially opening pore"  "http://data.bioontology.org/provisional_classes/3a694e40-e12b-0132-ac85-005056010074"  ""  "http://purl.obolibrary.org/obo/PATO_0000025"  "composition"  "http://purl.obolibrary.org/obo/UBERON_0008915"  "pore"  "composition, structure"
        "McLennan, D. A., & Mattern, M. Y. (2001)"  "12"  "Interorbital commisure"  "1"  "medially opening pore"  "http://data.bioontology.org/provisional_classes/3a694e40-e12b-0132-ac85-005056010074"  ""  "http://purl.obolibrary.org/obo/PATO_0000025"  "composition"  "http://purl.obolibrary.org/obo/UBERON_0008915"  "pore"  "composition, structure"
        
# Group Terms

##  Term detail [/term{?iri}]
### Return detail info for a given term. Currently this is the label and an optional definition [GET]
+ Parameters
    + iri (required, URI, `http://purl.obolibrary.org/obo/UBERON_0011618`) ... the term IRI
+ Response 200 (application/json)

## Term search [/term/search{?text,type,property}]
### Search for terms in the KB by text match on a property value. `rdfs:label` is searched by default. [GET]
+ Parameters
    + text (required, string, `basihyal`) ... the input text to search
    + type (optional, URI, `http://www.w3.org/2002/07/owl#Class`) ... the type of term to search for
    + property (optional, URI, `http://www.w3.org/2000/01/rdf-schema#label`)
+ Response 200 (application/json)

        {
        "results": [
            {
            "@id": "http://purl.obolibrary.org/obo/UBERON_3000957",
            "label": "basihyal"
            }, {
            "@id": "http://purl.obolibrary.org/obo/XAO_0004358",
            "label": "basihyal"
            }, {
            "@id": "http://purl.obolibrary.org/obo/UBERON_0011618",
            "label": "basihyal bone"
            }, {
            "@id": "http://purl.obolibrary.org/obo/ZFA_0000316",
            "label": "basihyal bone"
            }, {
            "@id": "http://purl.obolibrary.org/obo/UBERON_0011615",
            "label": "basihyal cartilage"
            }, {
            "@id": "http://purl.obolibrary.org/obo/ZFA_0001510",
            "label": "basihyal cartilage"
            }
        ]
        }
        
        
##  Ontology class search [/term/search_classes{?text,definedBy,limit}]
### Search for classes from a particular ontology [GET]
+ Parameters
    + text (required, string, `basihyal`) ... the input text to search
    + definedBy (URI, `http://purl.obolibrary.org/obo/uberon.owl`) ... the ontology identifier IRI in which the search terms are defined
    + limit (optional, integer, `10`)
+ Response 200 (application/json)

        {
        "results": [
            {
            "@id": "http://purl.obolibrary.org/obo/UBERON_3000957",
            "label": "basihyal"
            }, {
            "@id": "http://purl.obolibrary.org/obo/UBERON_0011618",
            "label": "basihyal bone"
            }, {
            "@id": "http://purl.obolibrary.org/obo/UBERON_0011615",
            "label": "basihyal cartilage"
            }
        ]
        }

##  Term label [/term/label{?iri}]
### Retrieve a label for a given term IRI [GET]
+ Parameters
    + iri (required, URI, `http://purl.obolibrary.org/obo/UBERON_0011618`) ... the term IRI
+ Response 200 (application/json)

        {
        "@id": "http://purl.obolibrary.org/obo/UBERON_0011618",
        "label": "basihyal bone"
        }
        
##  Term labels [/term/labels{?iris}]
### Retrieve a label for each term IRI in a list [GET]
+ Parameters
    + iris (required, URI, `http://purl.obolibrary.org/obo/UBERON_0011618,http://purl.obolibrary.org/obo/UBERON_0011615`) ... comma-separated list of term IRIs (no spaces)
+ Response 200 (application/json)

        {
        "results": [{
            "@id": "http://purl.obolibrary.org/obo/UBERON_0011615",
            "label": "basihyal cartilage"
        }, {
            "@id": "http://purl.obolibrary.org/obo/UBERON_0011618",
            "label": "basihyal bone"
        }]
        }
        
##  Classification [/term/classification{?iri}]
### Return direct superclasses, direct subclasses, and equivalent classes of a given term [GET]
+ Parameters
    + iri (required, URI, `http://purl.obolibrary.org/obo/UBERON_0011618`) ... the term IRI
+ Response 200 (application/json)

        {
        "@id": "http://purl.obolibrary.org/obo/UBERON_0011618",
        "label": "basihyal bone",
        "subClassOf": [{
            "@id": "http://purl.obolibrary.org/obo/UBERON_0011614",
            "label": "basihyal element"
            }, {
            "@id": "http://purl.obolibrary.org/obo/UBERON_0002513",
            "label": "endochondral bone"
        }],
        "equivalentTo": [],
        "superClassOf": [{
            "@id": "http://purl.obolibrary.org/obo/ZFA_0000316",
            "label": "basihyal bone"
        }]
        }
        
##  Ancestors [/term/all_ancestors{?iri}]
### Return all ancestor superclasses of a given term [GET]
+ Parameters
    + iri (required, URI, `http://purl.obolibrary.org/obo/UBERON_0011618`) ... the term IRI
+ Response 200 (application/json)

        {
          "results": [
            {
              "@id": "http://purl.obolibrary.org/obo/BFO_0000040",
              "label": "material entity"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/BFO_0000040",
              "label": "material entity"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/CARO_0000003",
              "label": "anatomical structure"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/CARO_0000003",
              "label": "anatomical structure"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/UBERON_0001474",
              "label": "bone element"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/UBERON_0000061",
              "label": "anatomical structure"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/UBERON_0000062",
              "label": "organ"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/UBERON_0000465",
              "label": "material anatomical entity"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/UBERON_0004119",
              "label": "endoderm-derived structure"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/UBERON_0004765",
              "label": "skeletal element"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/UBERON_0010000",
              "label": "multicellular anatomical structure"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/UBERON_0010314",
              "label": "structure with developmental contribution from neural crest"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/UBERON_0001062",
              "label": "anatomical entity"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/UBERON_0010363",
              "label": "endochondral element"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/UBERON_0002513",
              "label": "endochondral bone"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/UBERON_0011614",
              "label": "basihyal element"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/CARO_0000000",
              "label": "anatomical entity"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/CARO_0000006",
              "label": "material anatomical entity"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/CARO_0000006",
              "label": "material anatomical entity"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/CARO_0010000",
              "label": "multicellular anatomical structure"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/BFO_0000002",
              "label": "continuant"
            },
            {
              "@id": "http://purl.obolibrary.org/obo/BFO_0000004",
              "label": "independent continuant"
            }
          ]
        }

##  Descendants [/term/all_descendants{?iri}]
### Return all descendant subclasses of a given term [GET]
+ Parameters
    + iri (required, URI, `http://purl.obolibrary.org/obo/UBERON_0011618`) ... the term IRI
+ Response 200 (application/json)

        {
          "results": [
            {
              "@id": "http://purl.obolibrary.org/obo/ZFA_0000316",
              "label": "basihyal bone"
            }
          ]
        }        

## Least common subsumers [/term/least_common_subsumers{?iris,definedBy}]     
### Return the set of least common subsumers for a set of terms [GET]
For any set of input terms, there may be more than one least common subsumer. This is because the Phenoscape KB class hierarchy is not a strict tree, but more generally a directed acyclic graph with multiple axes of classification.
+ Parameters
    + iris (required, URI, `http://purl.obolibrary.org/obo/UBERON_4200115,http://purl.obolibrary.org/obo/UBERON_4000160`) ... comma-separated list of term IRIs (no spaces)
    + definedBy (optional, URI, `http://purl.obolibrary.org/obo/uberon.owl`) ... limit the returned subsumers to those defined by this ontology
+ Response 200 (application/json)

        {
        "results": [{
            "@id": "http://purl.obolibrary.org/obo/UBERON_0007829"
            }, {
            "@id": "http://purl.obolibrary.org/obo/UBERON_0008907"
        }]
        }

# Group OntoTrace

## OntoTrace [/ontotrace{?taxon,entity,variable_only}]
### Generate matrix of inferred presence/absence associations for anatomical structures subsumed by the provided entity class expression, for any taxa within the provided taxon class expression [GET]
Returns a NeXML-format evolutionary character matrix.
+ Parameters
    + taxon (required, string, `<http://purl.obolibrary.org/obo/VTO_0036217>`) ... Taxonomic class expression in [OWL Manchester syntax](http://www.w3.org/TR/owl2-manchester-syntax/)
    + entity (required, string `<http://purl.obolibrary.org/obo/BFO_0000050> some <http://purl.obolibrary.org/obo/UBERON_0008897>`) ... Anatomical class expression in [OWL Manchester syntax](http://www.w3.org/TR/owl2-manchester-syntax/)
    + variable_only (optional, boolean, `true`) ... whether to restrict the matrix to characters with both 'present' and 'absent' values in the matrix
+ Response 200 (application/xml) 

        <?xml version="1.0" encoding="UTF-8"?>
        <nexml xmlns="http://www.nexml.org/2009" xmlns:dc="http://purl.org/dc/terms/" xmlns:dwc="http://rs.tdwg.org/dwc/terms/" xmlns:obo="http://purl.obolibrary.org/obo/" xmlns:ps="http://vocab.phenoscape.org/" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.9" xsi:schemaLocation="http://www.nexml.org/2009 http://www.nexml.org/2009/nexml.xsd http://www.bioontologies.org/obd/schema/pheno http://purl.org/phenoscape/phenoxml.xsd">
          <meta xsi:type="LiteralMeta" property="dc:creator" />
          <meta xsi:type="LiteralMeta" property="dc:description">Generated from the Phenoscape Knowledgebase on 2015-10-20 by Ontotrace query:
        * taxa: &lt;http://purl.obolibrary.org/obo/VTO_0036217&gt;
        * entities: &lt;http://purl.obolibrary.org/obo/BFO_0000050&gt; some &lt;http://purl.obolibrary.org/obo/UBERON_0008897&gt;</meta>
          <otus id="ta2272552-0b69-46ce-ac61-c653f7fb8e73">
            <otu id="VTO_0036225" label="Ictalurus punctatus" about="#VTO_0036225">
              <meta xsi:type="ResourceMeta" rel="dwc:taxonID" href="http://purl.obolibrary.org/obo/VTO_0036225" />
            </otu>
            <otu id="VTO_0061498" label="Ictalurus mexicanus" about="#VTO_0061498">
              <meta xsi:type="ResourceMeta" rel="dwc:taxonID" href="http://purl.obolibrary.org/obo/VTO_0061498" />
            </otu>
            <otu id="VTO_0061495" label="Ictalurus australis" about="#VTO_0061495">
              <meta xsi:type="ResourceMeta" rel="dwc:taxonID" href="http://purl.obolibrary.org/obo/VTO_0061495" />
            </otu>
            <otu id="VTO_0036221" label="Ictalurus balsanus" about="#VTO_0036221">
              <meta xsi:type="ResourceMeta" rel="dwc:taxonID" href="http://purl.obolibrary.org/obo/VTO_0036221" />
            </otu>
            <otu id="VTO_0036218" label="Ictalurus pricei" about="#VTO_0036218">
              <meta xsi:type="ResourceMeta" rel="dwc:taxonID" href="http://purl.obolibrary.org/obo/VTO_0036218" />
            </otu>
            <otu id="VTO_0036223" label="Ictalurus furcatus" about="#VTO_0036223">
              <meta xsi:type="ResourceMeta" rel="dwc:taxonID" href="http://purl.obolibrary.org/obo/VTO_0036223" />
            </otu>
            <otu id="VTO_0036220" label="Ictalurus lupus" about="#VTO_0036220">
              <meta xsi:type="ResourceMeta" rel="dwc:taxonID" href="http://purl.obolibrary.org/obo/VTO_0036220" />
            </otu>
            <otu id="VTO_0061497" label="Ictalurus dugesii" about="#VTO_0061497">
              <meta xsi:type="ResourceMeta" rel="dwc:taxonID" href="http://purl.obolibrary.org/obo/VTO_0061497" />
            </otu>
            <otu id="VTO_0061496" label="Ictalurus sp. (Mo 1991)" about="#VTO_0061496">
              <meta xsi:type="ResourceMeta" rel="dwc:taxonID" href="http://purl.obolibrary.org/obo/VTO_0061496" />
            </otu>
          </otus>
          <characters id="cf52803f-e302-4ae7-9242-4d8c8daf7bde" xsi:type="StandardCells" otus="ta2272552-0b69-46ce-ac61-c653f7fb8e73">
            <format>
              <states id="s62693495-2c47-4a2d-ae7c-10e1b033cc99">
                <state id="UBERON_2002002_1" label="present" symbol="1" />
                <state id="UBERON_2002002_0" label="absent" symbol="0" />
                <polymorphic_state_set id="sb2f789a5-1727-4db4-a8bf-b7260742575d" symbol="1 and 0">
                  <member state="UBERON_2002002_1" />
                  <member state="UBERON_2002002_0" />
                </polymorphic_state_set>
              </states>
              <states id="s8ddf6f6e-b946-456f-9906-0dc41966f1c4">
                <state id="UBERON_2001788_1" label="present" symbol="1" />
                <state id="UBERON_2001788_0" label="absent" symbol="0" />
                <polymorphic_state_set id="s70c8320f-d62a-47a4-b7ca-4ad7455fd2b0" symbol="1 and 0">
                  <member state="UBERON_2001788_1" />
                  <member state="UBERON_2001788_0" />
                </polymorphic_state_set>
              </states>
              <states id="s80e10fab-6506-4b72-892b-8e4ac261eb4a">
                <state id="UBERON_2002001_1" label="present" symbol="1" />
                <state id="UBERON_2002001_0" label="absent" symbol="0" />
              </states>
              <char id="UBERON_2002002" label="anterior distal serration of pectoral fin spine" about="#UBERON_2002002" states="s62693495-2c47-4a2d-ae7c-10e1b033cc99">
                <meta xsi:type="ResourceMeta" rel="obo:IAO_0000219" href="http://purl.obolibrary.org/obo/UBERON_2002002" />
              </char>
              <char id="UBERON_2001788" label="pelvic splint" about="#UBERON_2001788" states="s8ddf6f6e-b946-456f-9906-0dc41966f1c4">
                <meta xsi:type="ResourceMeta" rel="obo:IAO_0000219" href="http://purl.obolibrary.org/obo/UBERON_2001788" />
              </char>
              <char id="UBERON_2002001" label="anterior dentation of pectoral fin spine" about="#UBERON_2002001" states="s80e10fab-6506-4b72-892b-8e4ac261eb4a">
                <meta xsi:type="ResourceMeta" rel="obo:IAO_0000219" href="http://purl.obolibrary.org/obo/UBERON_2002001" />
              </char>
            </format>
            <matrix>
              <row id="re5c991ac-0568-4d62-82e1-e54a3a88c296" otu="VTO_0036225">
                <cell char="UBERON_2002002" state="UBERON_2002002_1" />
                <cell char="UBERON_2001788" state="s70c8320f-d62a-47a4-b7ca-4ad7455fd2b0" />
                <cell char="UBERON_2002001" state="UBERON_2002001_1" />
              </row>
              <row id="re98d83f4-cc23-4014-a011-6b28e7fa876d" otu="VTO_0061498">
                <cell char="UBERON_2002002" state="UBERON_2002002_1" />
                <cell char="UBERON_2001788" state="UBERON_2001788_1" />
              </row>
              <row id="r3b75c894-6efc-46d7-96ae-bdc327f00c7b" otu="VTO_0061495">
                <cell char="UBERON_2002002" state="UBERON_2002002_1" />
                <cell char="UBERON_2001788" state="UBERON_2001788_1" />
                <cell char="UBERON_2002001" state="UBERON_2002001_1" />
              </row>
              <row id="r13b318e3-309d-4e6b-9306-68e1ed765cc6" otu="VTO_0036221">
                <cell char="UBERON_2002002" state="sb2f789a5-1727-4db4-a8bf-b7260742575d" />
                <cell char="UBERON_2001788" state="UBERON_2001788_1" />
                <cell char="UBERON_2002001" state="UBERON_2002001_0" />
              </row>
              <row id="rc80b1386-ea71-4f28-a26f-a442bb75ae6d" otu="VTO_0036218">
                <cell char="UBERON_2002002" state="UBERON_2002002_1" />
                <cell char="UBERON_2001788" state="UBERON_2001788_1" />
                <cell char="UBERON_2002001" state="UBERON_2002001_1" />
              </row>
              <row id="rb855c9cc-8594-41f3-bb1e-f85ca1b5ce94" otu="VTO_0036223">
                <cell char="UBERON_2002002" state="UBERON_2002002_1" />
                <cell char="UBERON_2001788" state="UBERON_2001788_1" />
                <cell char="UBERON_2002001" state="UBERON_2002001_0" />
              </row>
              <row id="redbdfca0-ca69-4710-a887-b9429c3faf67" otu="VTO_0036220">
                <cell char="UBERON_2002002" state="UBERON_2002002_1" />
                <cell char="UBERON_2001788" state="UBERON_2001788_1" />
                <cell char="UBERON_2002001" state="UBERON_2002001_1" />
              </row>
              <row id="r4378658a-901f-464f-9320-c9375ead4638" otu="VTO_0061497">
                <cell char="UBERON_2002002" state="UBERON_2002002_1" />
                <cell char="UBERON_2001788" state="UBERON_2001788_1" />
              </row>
              <row id="r0034d445-b7ec-4246-af54-68a90afc718d" otu="VTO_0061496">
                <cell char="UBERON_2001788" state="UBERON_2001788_0" />
              </row>
            </matrix>
          </characters>
          <trees id="td2cf438a-4bef-49b0-93cf-7a0a97660a58" otus="ta2272552-0b69-46ce-ac61-c653f7fb8e73" />
        </nexml>


# Group Semantic Similarity

## Semantic similarity query [/similarity/query{?iri,limit,offset}]
### Retrieve taxon variation profile similarity scores for this gene, ordered with best matches first [GET]
+ Parameters
    + iri (required, URI, `http://www.informatics.jax.org/marker/MGI:1202401`) ... Gene IRI
    + limit (optional, integer `20`)
    + offset (optional, integer, `0`)
+ Response 200 (text/plain)

        taxon IRI    taxon label    median score    expect score
        http://purl.obolibrary.org/obo/VTO_0037378    Gymnotiformes    0.7506756923676524    0.0014462288121
        http://purl.obolibrary.org/obo/VTO_0037490    Eigenmannia    0.6217930498438566    0.00352135614022
        
+ Response 200 (application/json)

        {
        "results": [{
        "match_profile": {
            "@id": "http://purl.obolibrary.org/obo/VTO_0037378",
            "label": "Gymnotiformes"
        },
        "median_score": 0.7506756923676524,
        "expect_score": 0.0014462288121
        }, {
        "match_profile": {
        "@id": "http://purl.obolibrary.org/obo/VTO_0037490",
        "label": "Eigenmannia"
        },
        "median_score": 0.6217930498438566,
        "expect_score": 0.00352135614022
        }]
        }

## Best annotation matches for comparison [/similarity/best_matches{?query_iri,corpus_iri}]
### Retrieve the top matching phenotype annotations, with their most informative common subsumer, for a given pair of profiles, e.g. a gene and a taxon [GET]
+ Parameters
    + query_iri (required, URI, `http://www.informatics.jax.org/marker/MGI:1202401`) ... IRI for query profile    
    + corpus_iri (required, URI, `http://purl.obolibrary.org/obo/VTO_0037378`) ... IRI for matched profile in corpus
+ Response 200 (application/json)

        {
        "results": [{
            "query_annotation": {
                "@id": "http://purl.obolibrary.org/obo/MP_0009038",
                "label": "decreased inferior colliculus size"
            },
            "corpus_annotation": {
                "@id": "http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000140%3E+and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2002106%3E%29+and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2Fpato%23towards%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001945%3E%29#ca1edf06-51cb-40f5-8858-0b266e906ca2",
                "label": "position and (inheres in some eminentia granularis) and (towards some superior colliculus)"
            },
            "best_subsumer": {
                "term": {
                    "@id": "http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%28%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23phenotype_of%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002950%3E%29",
                    "label": "has part some (phenotype of some regional part of midbrain)"
                },
                "ic": 0.8926218653448688,
                "disparity": 0.47824477007017246
            }
        }]
        }

## Best subsumers for comparison [/similarity/best_subsumers{?query_iri,corpus_iri}]
### Retrieve only the most informative subsumers for the top matching phenotype annotations for a given pair of profiles, e.g. a gene and a taxon [GET]
+ Parameters
    + query_iri (required, URI, `http://www.informatics.jax.org/marker/MGI:1202401`) ... IRI for query profile    
    + corpus_iri (required, URI, `http://purl.obolibrary.org/obo/VTO_0037378`) ... IRI for matched profile in corpus
+ Response 200 (application/json)

        {
        "results": [{
            "term": {
            "@id": "http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%28%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23phenotype_of%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002950%3E%29",
            "label": "has part some (phenotype of some regional part of midbrain)"
            },
            "ic": 0.8926218653448688
        }, {
            "term": {
            "@id": "http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000051%3E+some+%28%3Chttp%3A%2F%2Fpurl.org%2Fphenoscape%2Fvocab.owl%23phenotype_of%3E+some+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000050%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0003528%3E%29%29",
            "label": "has part some (phenotype of some (part of some brain grey matter))"
            },
            "ic": 0.7506756923676524
        }]
        }
        
## Subsumed annotations [/similarity/subsumed_annotations{?subsumer,instance}]
### Retrieve all annotations for a given profile which are subsumed by a phenotype class [GET]
+ Parameters
    + subsumer (required, URI, `http://purl.obolibrary.org/obo/MP_0001265`) ... IRI for query profile    
    + instance (required, URI, `http://www.informatics.jax.org/marker/MGI:1202401`) ... IRI for matched profile in corpus
+ Response 200 (application/json)

        {
        "results": [{
            "@id": "http://purl.obolibrary.org/obo/MP_0009038",
            "label": "decreased inferior colliculus size"
        }]
        }

## Profile size [/similarity/profile_size{?iri}]
### Retrieve number of phenotype annotations for a given profile, e.g. gene or taxon [GET]
+ Parameters
    + iri (required, URI, `http://www.informatics.jax.org/marker/MGI:1202401`) ... IRI for profile    
+ Response 200 (application/json)

        {
        "total": 5
        }
        
## Corpus size [/similarity/corpus_size]
### Retrieve number of instances in the similarity search corpus (currently, taxon nodes) [GET]
+ Response 200 (application/json)

        {
        "total": 659
        }
        
## IC disparity [/similarity/ic_disparity{?iri}]
### Query information content disparity for a phenotype class between taxon and gene corpora [GET]
The disparity for a class is the taxon-based IC minus the gene-based IC.
+ Parameters
    + iri (required, URI, `http://purl.obolibrary.org/obo/PATO_0000052`) ... IRI for phenotype class
+ Response 200 (application/json)

        {
        "value": -0.19564677483705345
        } 


# Group Taxa

##  Taxon info [/taxon{?iri}]
### Return detail info for a given taxon. [GET]
Currently this is the label, extinction status, and an optional rank.
+ Parameters
    + iri (required, URI, `http://purl.obolibrary.org/obo/VTO_9020379`) ... the taxon IRI
+ Response 200 (application/json)

        {
        "@id": "http://purl.obolibrary.org/obo/VTO_9020379",
        "label": "Diplocaulus",
        "extinct": true,
        "rank": {
            "@id": "http://purl.obolibrary.org/obo/TAXRANK_0000005",
            "label": "genus"
        }
        }

## Taxon phenotypes [/taxon/phenotypes{?taxon,limit,offset,total}]
### Retrieve direct phenotype annotations for a given taxon [GET]
+ Parameters
    + taxon (required, URI, `http://purl.obolibrary.org/obo/VTO_0036225`) ... IRI for taxon    
    + limit (optional, integer, `20`)
    + offset (optional, integer, `0`)
    + total (optional, boolean, `false`) ... whether to return the total result count rather than the results
+ Response 200 (application/json)

        {
        "results": [{
            "@id": "http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000025%3E+and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0006606%3E%29#b37d4b42-92e8-41d9-930c-40592efe6d27"
        }, {
            "@id": "http://purl.org/phenoscape/expression?value=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000025%3E+and+%28%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000052%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0006860%3E%29#911a4756-23dc-47af-ac2e-ddb70d844458"
        }]
        }

+ Response 200 (application/json)

        {
        "total": 803
        }
        
# Group Genes

##  Gene info [/gene{?iri}]
### Return detail info for a given gene [GET]
Currently this is the label and taxon.
+ Parameters
    + iri (required, URI, `http://zfin.org/ZDB-GENE-040426-731`) ... the gene IRI
+ Response 200 (application/json)

## Gene search [/gene/search{?text,taxon}]
### Search for genes by gene symbol [GET]
Returns matched genes with taxon info for each. Requests can optionally filter by a specific model organism taxon. Current valid taxa are:

* `http://purl.obolibrary.org/obo/NCBITaxon_7955` _Danio_ _rerio_ (zebrafish)
* `http://purl.obolibrary.org/obo/NCBITaxon_10090` _Mus_ _musculus_ (mouse)
* `http://purl.obolibrary.org/obo/NCBITaxon_8353` _Xenopus_ (frog)
* `http://purl.obolibrary.org/obo/NCBITaxon_9606` _Homo_ _sapiens_ (human)

+ Parameters
    + text (required, String, `brpf1`) ... text to match in the gene symbol
    + taxon (optional, URI, `http://purl.obolibrary.org/obo/NCBITaxon_7955`) ... NCBI IRI for taxon    
+ Response 200 (application/json)

        {
          "results": [{
            "@id": "http://zfin.org/ZDB-GENE-040426-731",
            "label": "brpf1",
            "taxon": {
              "@id": "http://purl.obolibrary.org/obo/NCBITaxon_7955",
              "label": "zebrafish"
            }
          }, {
            "@id": "http://www.informatics.jax.org/marker/MGI:1926033",
            "label": "Brpf1",
            "taxon": {
              "@id": "http://purl.obolibrary.org/obo/NCBITaxon_10090",
              "label": "mouse"
            }
          }]
        }

+ Response 200 (text/plain)

        IRI    label    taxon
        http://zfin.org/ZDB-GENE-040426-731    brpf1    zebrafish
        http://www.informatics.jax.org/marker/MGI:1926033    Brpf1    mouse

# Group Studies
Services related to studies providing evolutionary data matrices for annotation.

## Query studies by taxa and anatomical entity [/study/query{?taxon,entity}]
### Return studies containing taxa which are members of the optional input taxon expression and are have annotated phenotypes which are relevant to the optional input entity expression. [GET]
+ Parameters
    + taxon (required, string, `<http://purl.obolibrary.org/obo/VTO_0036217>`) ... Taxonomic class expression in [OWL Manchester syntax](http://www.w3.org/TR/owl2-manchester-syntax/)
    + entity (required, string `<http://purl.obolibrary.org/obo/BFO_0000050> some <http://purl.obolibrary.org/obo/UBERON_0008897>`) ... Anatomical class expression in [OWL Manchester syntax](http://www.w3.org/TR/owl2-manchester-syntax/)
+ Response 200 (application/json)

        {
          "results": [{
            "@id": "https://scholar.google.com/scholar?q=Higher-level+Phylogeny+of+Siluriformes%2C+With+a+New+Classification+of+the+Order+%28Teleostei%2C+Ostariophysi%29&btnG=&hl=en&as_sdt=0%2C42",
            "label": "De Pinna, M. C. (1993)"
          }, {
            "@id": "http://dx.doi.org/10.1111/j.1096-3642.1981.tb01575.x",
            "label": "Fink, S. V, & Fink, W. L. (1981);  Fink, S. V, & Fink, W. L. (1996)"
          }, {
            "@id": "http://search.informit.com.au/documentSummary;dn=057273049071593;res=IELHSS",
            "label": "Kailola, P. J. (2004)"
          }, {
            "@id": "https://scholar.google.com/scholar?q=The+Phylogeny+of+Ictalurid+Catfishes%3A+A+Synthesis+of+Recent+Work&btnG=&hl=en&as_sdt=0%2C42",
            "label": "Lundberg, J. G. (1992)"
          }, {
            "@id": "https://scholar.google.com/scholar?q=Anatomy%2C+relationships+and+systematics+of+the+Bagridae+%28Teleostei%3A+Siluroidei%29+with+a+hypothesis+of+siluroid+phylogeny+by&btnG=&hl=en&as_sdt=0%2C42",
            "label": "Mo, T. (1991)"
          }, {
            "@id": "https://scholar.google.com/scholar?q=Studies+on+the+systematics+and+phylogeny+of+the+catfish+family+Auchenipteridae+%28Teleostei%3A+Siluriformes%29&btnG=&hl=en&as_sdt=0%2C42",
            "label": "Royero, R. (1999)"
          }, {
            "@id": "http://www.bioone.org/doi/abs/10.1635/0097-3157(2008)157%5B73:APSOTA%5D2.0.CO%3B2",
            "label": "Vigliotta, T. R. (2008)"
          }]
        }

## Data matrix for study [/study/matrix{?iri}]
*This service is not yet implemented.*
### Return a data matrix in NeXML format containing the data for a given study [GET]

+ Parameters
    + iri (required, URI, `http://dx.doi.org/10.1111/j.1096-3642.2008.00407.x`) ... the study IRI
+ Response 200 (application/xml)


# Group not yet updated       

## EQ for gene [/gene/eq{?id}]
### Return most direct UBERON entities and PATO qualities for all phenotype annotations associated with a gene [GET]
+ Parameters
    + id (required, URI) ... Identifier for a gene
+ Response 200 (application/json)

        {
        "@id": "http://zfin.org/ZDB-GENE-040426-731",
        "label": "brpf1",
        "taxon": {
            "@id": "http://purl.obolibrary.org/obo/NCBITaxon_7955",
            "label": "zebrafish"
            }
        }  

## Evidence for presence of a structure [/entity/presence{?taxon,entity}]
### Return any character states which entail the presence of an anatomical structure within a taxon [GET]
+ Parameters
  + taxon (required, URI, `http://purl.obolibrary.org/obo/VTO_0034991`) ... Identifier of a taxonomic group
  + entity (required, URI, `http://purl.obolibrary.org/obo/UBERON_4000164`) ... Identifier of an anatomical structure
+ Response 200 (text/tsv)

## Evidence for absence of a structure [/entity/absence{?taxon,entity}]
### Return any character states which entail the absence of an anatomical structure within a taxon [GET]
+ Parameters
  + taxon (required, URI, `http://purl.obolibrary.org/obo/VTO_0034991`) ... Identifier of a taxonomic group
  + entity (required, URI, `http://purl.obolibrary.org/obo/UBERON_0002542`) ... Identifier of an anatomical structure
+ Response 200 (text/tsv)
