FORMAT: 1A
HOST: http://kb.phenoscape.org/api/

# Phenoscape Knowledgebase web API
The Phenoscape Knowledgebase web API is an HTTP interface for searching ontology terms, retrieving term info, and querying data from the KB.

##  Term detail [/term{?iri}]
### Return detail info for a given term. Currently this is the label and an optional definition [GET]
+ Parameters
    + iri (required, URI, `http://purl.obolibrary.org/obo/UBERON_0011618`) ... the term IRI
+ Response 200 (application/json)

## Term search [/term/search{?text,type,property}]
### Search for terms in the KB by text match on a property value. `rdfs:label` is searched by default. [GET]
+ Parameters
    + text (required, string, `basihyal`) ... the input text to search
    + type (optional, URI, `http://www.w3.org/2002/07/owl#Class`) ... the type of term to search for
    + property (optional, URI, `http://www.w3.org/2000/01/rdf-schema#label`)
+ Response 200 (application/json)

        {
        "results": [
            {
            "@id": "http://purl.obolibrary.org/obo/UBERON_3000957",
            "label": "basihyal"
            }, {
            "@id": "http://purl.obolibrary.org/obo/XAO_0004358",
            "label": "basihyal"
            }, {
            "@id": "http://purl.obolibrary.org/obo/UBERON_0011618",
            "label": "basihyal bone"
            }, {
            "@id": "http://purl.obolibrary.org/obo/ZFA_0000316",
            "label": "basihyal bone"
            }, {
            "@id": "http://purl.obolibrary.org/obo/UBERON_0011615",
            "label": "basihyal cartilage"
            }, {
            "@id": "http://purl.obolibrary.org/obo/ZFA_0001510",
            "label": "basihyal cartilage"
            }
        ]
        }
        
        
##  Ontology class search [/term/search_classes{?text,definedBy,limit}]
### Search for classes from a particular ontology [GET]
+ Parameters
    + text (required, string, `basihyal`) ... the input text to search
    + definedBy (URI, `http://purl.obolibrary.org/obo/uberon.owl`) ... the ontology identifier IRI in which the search terms are defined
    + limit (optional, integer, `10`)
+ Response 200 (application/json)

        {
        "results": [
            {
            "@id": "http://purl.obolibrary.org/obo/UBERON_3000957",
            "label": "basihyal"
            }, {
            "@id": "http://purl.obolibrary.org/obo/UBERON_0011618",
            "label": "basihyal bone"
            }, {
            "@id": "http://purl.obolibrary.org/obo/UBERON_0011615",
            "label": "basihyal cartilage"
            }
        ]
        }

##  Term label [/term/label{?iri}]
### Retrieve a label for a given term IRI [GET]
+ Parameters
    + iri (required, URI, `http://purl.obolibrary.org/obo/UBERON_0011618`) ... the term IRI
+ Response 200 (application/json)

        {
        "@id": "http://purl.obolibrary.org/obo/UBERON_0011618",
        "label": "basihyal bone"
        }
        
##  Term labels [/term/labels{?iris}]
### Retrieve a label for each term IRI in a list [GET]
+ Parameters
    + iris (required, URI, `http://purl.obolibrary.org/obo/UBERON_0011618,http://purl.obolibrary.org/obo/UBERON_0011615`) ... comma-separated list of term IRIs (no spaces)
+ Response 200 (application/json)

        {
        "results": [{
            "@id": "http://purl.obolibrary.org/obo/UBERON_0011615",
            "label": "basihyal cartilage"
        }, {
            "@id": "http://purl.obolibrary.org/obo/UBERON_0011618",
            "label": "basihyal bone"
        }]
        }
        
##  Classification [/term/classification{?iri}]
### Return direct superclasses, direct subclasses, and equivalent classes of a given term [GET]
+ Parameters
    + iri (required, URI, `http://purl.obolibrary.org/obo/UBERON_0011618`) ... the term IRI
+ Response 200 (application/json)

        {
        "@id": "http://purl.obolibrary.org/obo/UBERON_0011618",
        "label": "basihyal bone",
        "subClassOf": [{
            "@id": "http://purl.obolibrary.org/obo/UBERON_0011614",
            "label": "basihyal element"
            }, {
            "@id": "http://purl.obolibrary.org/obo/UBERON_0002513",
            "label": "endochondral bone"
        }],
        "equivalentTo": [],
        "superClassOf": [{
            "@id": "http://purl.obolibrary.org/obo/ZFA_0000316",
            "label": "basihyal bone"
        }]
        }

## Ontotrace [/ontotrace{?taxon,entity,variable_only}]
### Generate matrix of inferred presence/absence associations for anatomical structures subsumed by the provided entity class expression, for any taxa within the provided taxon class expression [GET]
Returns a NeXML-format evolutionary character matrix.
+ Parameters
    + taxon (required, string, `<http://purl.obolibrary.org/obo/VTO_0036217>`) ... Taxonomic class expression in [OWL Manchester syntax](http://www.w3.org/TR/owl2-manchester-syntax/)
    + entity (required, string `<http://purl.obolibrary.org/obo/BFO_0000050> some <http://purl.obolibrary.org/obo/UBERON_0008897>`) ... Anatomical class expression in [OWL Manchester syntax](http://www.w3.org/TR/owl2-manchester-syntax/)
    + variable_only (optional, boolean, `true`) ... whether to restrict the matrix to characters with both 'present' and 'absent' values in the matrix
+ Response 200 (application/xml) 

## Genes affecting phenotype [/genes_affecting_phenotype{?entity,quality}]
### Search for genes affecting phenotype of any part of a structure [GET]
+ Parameters
  + entity (required, URI, `http://purl.obolibrary.org/obo/UBERON_0002101`) ... Identifier of an anatomical structure
  + quality (required, URI, `http://purl.obolibrary.org/obo/PATO_0000052`) ... Identifier of phenotypic quality
+ Response 200 (text/tsv)

        ?gene ?gene_label_string ?taxon_label_string ?source
        <http://www.informatics.jax.org/marker/MGI:88302> Ccnb1 Mus musculus <http://www.informatics.jax.org/reference/summary?id=J:46439>
        <http://www.informatics.jax.org/marker/MGI:95834> Pdia3 Mus musculus <http://www.informatics.jax.org/reference/summary?id=J:98374>

## Genes expressed within a structure [/genes_expressed_in_structure{?iri}]
### Search for genes expressed within any part of a structure [GET]
+ Parameters
  + iri (required, URI, `http://purl.obolibrary.org/obo/UBERON_0002101`) ... Identifier of an anatomical structure
+ Response 200 (text/tsv)

        ?gene ?gene_label_string ?taxon_label_string ?source
        <http://www.informatics.jax.org/marker/MGI:88302> Ccnb1 Mus musculus <http://www.informatics.jax.org/reference/summary?id=J:46439>
        <http://www.informatics.jax.org/marker/MGI:95834> Pdia3 Mus musculus <http://www.informatics.jax.org/reference/summary?id=J:98374>

## EQ for gene [/gene/eq{?id}]
### Return most direct UBERON entities and PATO qualities for all phenotype annotations associated with a gene [GET]
+ Parameters
    + id (required, URI) ... Identifier for a gene
+ Response 200 (application/json)

## Evidence for presence of a structure [/entity/presence{?taxon,entity}]
### Return any character states which entail the presence of an anatomical structure within a taxon [GET]
+ Parameters
  + taxon (required, URI, `http://purl.obolibrary.org/obo/VTO_0034991`) ... Identifier of a taxonomic group
  + entity (required, URI, `http://purl.obolibrary.org/obo/UBERON_4000164`) ... Identifier of an anatomical structure
+ Response 200 (text/tsv)

## Evidence for absence of a structure [/entity/absence{?taxon,entity}]
### Return any character states which entail the absence of an anatomical structure within a taxon [GET]
+ Parameters
  + taxon (required, URI, `http://purl.obolibrary.org/obo/VTO_0034991`) ... Identifier of a taxonomic group
  + entity (required, URI, `http://purl.obolibrary.org/obo/UBERON_0002542`) ... Identifier of an anatomical structure
+ Response 200 (text/tsv)
