name: Scala CI

on:
  push:
    branches:
      - master
      - services-new-data-model
      - relations-graphs-updates
      - 2.0-maintenance
  pull_request:
    branches:
      - master
      - services-new-data-model
      - relations-graphs-updates 
      - 2.0-maintenance
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run tests
      run: sbt test
