name: Scala CI

on:
  push:
    branches:
      - master
      - services-new-data-model
      - relations-graphs-updates
  pull_request:
    branches:
      - master
      - services-new-data-model
      - relations-graphs-updates 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt test
